const { db, Emoji } = require("./prisma/schema.prisma")
const animalEmojis = [
  {
    emoji: "😺",
    name: "grinning-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/grinning-cat_1f63a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😸",
    name: "grinning-cat-with-smiling-eyes",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/grinning-cat-with-smiling-eyes_1f638.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😹",
    name: "cat-with-tears-of-joy",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/cat-with-tears-of-joy_1f639.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😻",
    name: "smiling-cat-with-heart-eyes",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/smiling-cat-with-heart-eyes_1f63b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😼",
    name: "cat-with-wry-smile",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/cat-with-wry-smile_1f63c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😽",
    name: "kissing-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/kissing-cat_1f63d.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🙀",
    name: "weary-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/weary-cat_1f640.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😿",
    name: "crying-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/crying-cat_1f63f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "😾",
    name: "pouting-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/pouting-cat_1f63e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🙈",
    name: "see-no-evil-monkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/see-no-evil-monkey_1f648.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🙉",
    name: "hear-no-evil-monkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/hear-no-evil-monkey_1f649.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🙊",
    name: "speak-no-evil-monkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/speak-no-evil-monkey_1f64a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐵",
    name: "monkey-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/72/google/350/monkey-face_1f435.png",
    aColor: "#B7895A",
    bColor: "#FFCE89",
    cColor: "#36322D",
    dColor: "#FF6B10",
    eColor: "null",
  },
  {
    emoji: "🐒",
    name: "monkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/monkey_1f412.png",
    aColor: "#B7895A",
    bColor: "#FFCE90",
    cColor: "#36322D",
    dColor: "#FF6B11",
    eColor: "#855A53",
  },
  {
    emoji: "🦍",
    name: "gorilla",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/gorilla_1f98d.png",
    aColor: "#5D6265",
    bColor: "#AFB0B1",
    cColor: "#A8A9A9",
    dColor: "#3A3D3F",
    eColor: "#000000",
  },
  {
    emoji: "🦧",
    name: "orangutan",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/orangutan_1f9a7.png",
    aColor: "#FE5E0A",
    bColor: "#8E5E4F",
    cColor: "#4F3329",
    dColor: "#BB967F",
    eColor: "#D37955",
  },
  {
    emoji: "🐶",
    name: "dog-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dog-face_1f436.png",
    aColor: "#ffeac8",
    bColor: "#865b51",
    cColor: "#e09c7a",
    dColor: "#2f2f2f",
    eColor: "#ea5894",
  },
  {
    emoji: "🐕",
    name: "dog",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/dog_1f415.png",
    aColor: "#ffd2b1",
    bColor: "#865b52",
    cColor: "#d27856",
    dColor: "#8c5039",
    eColor: "#000000",
  },
  {
    emoji: "🦮",
    name: "guide-dog",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/guide-dog_1f9ae.png",
    aColor: "#ffb903",
    bColor: "#d1775b",
    cColor: "#a56653",
    dColor: "#abb0b1",
    eColor: "#0ac2e7",
  },
  {
    emoji: "🐕‍🦺",
    name: "service-dog",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/service-dog_1f415-200d-1f9ba.png",
    aColor: "#f1a058",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐩",
    name: "poodle",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/poodle_1f429.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐺",
    name: "wolf",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/wolf_1f43a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦊",
    name: "fox",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/fox_1f98a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦝",
    name: "raccoon",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/raccoon_1f99d.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐱",
    name: "cat-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/cat-face_1f431.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐈",
    name: "cat",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/cat_1f408.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐈‍⬛",
    name: "black-cat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/black-cat_1f408-200d-2b1b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦁",
    name: "lion",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/lion_1f981.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐯",
    name: "tiger-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/tiger-face_1f42f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐅",
    name: "tiger",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/tiger_1f405.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐆",
    name: "leopard",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/leopard_1f406.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐴",
    name: "horse-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/horse-face_1f434.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐎",
    name: "horse",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/horse_1f40e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦄",
    name: "unicorn",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/unicorn_1f984.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦓",
    name: "zebra",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/zebra_1f993.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🫏",
    name: "donkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/donkey_1facf.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦌",
    name: "deer",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/deer_1f98c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🫎",
    name: "moose",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/120/google/350/moose_1face.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦬",
    name: "bison",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/bison_1f9ac.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐮",
    name: "cow-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/cow-face_1f42e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐂",
    name: "ox",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/ox_1f402.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐃",
    name: "water-buffalo",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/water-buffalo_1f403.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐄",
    name: "cow",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/cow_1f404.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐷",
    name: "pig-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/pig-face_1f437.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐖",
    name: "pig",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/pig_1f416.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐗",
    name: "boar",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/boar_1f417.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐏",
    name: "ram",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/ram_1f40f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐑",
    name: "ewe",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/ewe_1f411.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐐",
    name: "goat",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/goat_1f410.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐪",
    name: "camel",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/camel_1f42a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐫",
    name: "two-hump-camel",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/two-hump-camel_1f42b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦙",
    name: "llama",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/llama_1f999.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦒",
    name: "giraffe",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/giraffe_1f992.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐘",
    name: "elephant",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/elephant_1f418.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦣",
    name: "mammoth",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/mammoth_1f9a3.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦏",
    name: "rhinoceros",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/rhinoceros_1f98f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦛",
    name: "hippopotamus",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/hippopotamus_1f99b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐭",
    name: "mouse-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/mouse-face_1f42d.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐁",
    name: "mouse",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/mouse_1f401.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐀",
    name: "rat",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/rat_1f400.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐹",
    name: "hamster",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/hamster_1f439.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐰",
    name: "rabbit-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/rabbit-face_1f430.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐇",
    name: "rabbit",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/rabbit_1f407.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐿️",
    name: "chipmunk",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/chipmunk_1f43f-fe0f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦫",
    name: "beaver",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/beaver_1f9ab.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦔",
    name: "hedgehog",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/hedgehog_1f994.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦇",
    name: "bat",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/bat_1f987.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐻",
    name: "bear",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/bear_1f43b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐻‍❄️",
    name: "polar-bear",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/polar-bear_1f43b-200d-2744-fe0f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐨",
    name: "koala",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/koala_1f428.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐼",
    name: "panda",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/panda_1f43c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦥",
    name: "sloth",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/sloth_1f9a5.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦦",
    name: "otter",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/otter_1f9a6.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦨",
    name: "skunk",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/skunk_1f9a8.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦘",
    name: "kangaroo",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/kangaroo_1f998.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦡",
    name: "badger",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/badger_1f9a1.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐾",
    name: "paw-prints",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/paw-prints_1f43e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦃",
    name: "turkey",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/turkey_1f983.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐔",
    name: "chicken",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/chicken_1f414.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐓",
    name: "rooster",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/rooster_1f413.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐣",
    name: "hatching-chick",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/hatching-chick_1f423.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐤",
    name: "baby-chick",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/baby-chick_1f424.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐥",
    name: "front-facing-baby-chick",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/front-facing-baby-chick_1f425.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐦",
    name: "bird",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/bird_1f426.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐦‍⬛",
    name: "black-bird",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/black-bird_1f426-200d-2b1b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐧",
    name: "penguin",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/penguin_1f427.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🕊️",
    name: "dove",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dove_1f54a-fe0f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦅",
    name: "eagle",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/eagle_1f985.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦆",
    name: "duck",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/duck_1f986.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦢",
    name: "swan",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/swan_1f9a2.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪿",
    name: "goose",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/goose_1fabf.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦉",
    name: "owl",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/owl_1f989.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦤",
    name: "dodo",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dodo_1f9a4.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦩",
    name: "flamingo",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/flamingo_1f9a9.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦚",
    name: "peacock",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/peacock_1f99a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦜",
    name: "parrot",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/parrot_1f99c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐸",
    name: "frog",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/frog_1f438.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐊",
    name: "crocodile",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/crocodile_1f40a.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐢",
    name: "turtle",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/turtle_1f422.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦎",
    name: "lizard",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/lizard_1f98e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐍",
    name: "snake",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/snake_1f40d.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐲",
    name: "dragon-face",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dragon-face_1f432.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐉",
    name: "dragon",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dragon_1f409.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦕",
    name: "sauropod",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/sauropod_1f995.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦖",
    name: "t-rex",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/t-rex_1f996.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐳",
    name: "spouting-whale",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/spouting-whale_1f433.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐋",
    name: "whale",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/whale_1f40b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐬",
    name: "dolphin",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/dolphin_1f42c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦭",
    name: "seal",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/seal_1f9ad.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐟",
    name: "fish",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/fish_1f41f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐠",
    name: "tropical-fish",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/tropical-fish_1f420.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐡",
    name: "blowfish",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/blowfish_1f421.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦈",
    name: "shark",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/shark_1f988.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐙",
    name: "octopus",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/octopus_1f419.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪼",
    name: "jellyfish",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/jellyfish_1fabc.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐌",
    name: "snail",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/snail_1f40c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦋",
    name: "butterfly",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/butterfly_1f98b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐛",
    name: "bug",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/bug_1f41b.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐜",
    name: "ant",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/ant_1f41c.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐝",
    name: "honeybee",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/honeybee_1f41d.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪲",
    name: "beetle",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/beetle_1fab2.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🐞",
    name: "lady-beetle",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/lady-beetle_1f41e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦗",
    name: "cricket",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/cricket_1f997.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪳",
    name: "cockroach",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/cockroach_1fab3.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🕷️",
    name: "spider",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/spider_1f577-fe0f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦟",
    name: "mosquito",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/mosquito_1f99f.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪰",
    name: "fly",
    department: "animals",
    imageUrl: "https://em-content.zobj.net/thumbs/160/google/350/fly_1fab0.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🪱",
    name: "worm",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/worm_1fab1.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦀",
    name: "crab",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/crab_1f980.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦞",
    name: "lobster",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/lobster_1f99e.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦐",
    name: "shrimp",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/shrimp_1f990.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦑",
    name: "squid",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/squid_1f991.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  },
  {
    emoji: "🦪",
    name: "oyster",
    department: "animals",
    imageUrl:
      "https://em-content.zobj.net/thumbs/160/google/350/oyster_1f9aa.png",
    aColor: "",
    bColor: "",
    cColor: "",
    dColor: "",
    eColor: "",
  }
];

const seed = async () => {
  try{
    await db.sync({force:true});
    await Promise.all(animalEmojis.map(animal => {
      return Emoji.create(animal);

    }))
    console.log('🌰➤Seeding success!➤🌳')
    db.close()
  } catch(error){
    console.error('something went wrong')
    console.error(error)
    db.close()
  }
}
seed();
